#:kivy 2.0.0
RunWidget: # ルートに追加

<RunWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        # ラベル
        Label:
            id: label1
            font_size: 40
            text: root.label_text    # root(RunWidget)の変数テキストの値を取得

        Button:
            id: button1
            text: root.button_text
            font_size: 68
            size_hint_y: 0.2
            color: (71, 99, 225)
            on_press: root.run_openface()  # ボタンをクリックした時にpython側の関数を呼ぶ